apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  namespace: infra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
      - name: glpi
        image: diouxx/glpi:latest
        env:
        - name: TIMEZONE
          value: "Europe/Paris"
        - name: DB_HOST
          value: "10.0.20.10"
        - name: DB_NAME
          value: "glpi"
        - name: DB_USER
          value: "glpi"
        - name: DB_PASSWORD
          value: "pass"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: glpi
  namespace: infra
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30090
  selector:
    app: glpi