apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: MYSQL_HOST
          value: 192.168.1.31
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: pedro
        - name: MYSQL_PASSWORD
          value: pedro
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: infra
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30060
  selector:
    app: wordpress