apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        env:
        - name: MYSQL_HOST
          value: 192.168.1.31
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: pedro
        - name: MYSQL_PASSWORD
          value: pedro
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: glpi
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30060
  selector:
    app: nextcloud